apiVersion: apps/v1
kind: Deployment
metadata:
     name: mysql-deployment
     labels:
           app: mysql
spec:
     replicas: 1
     selector:
         matchLabels:
            app: mysql
     template:
         metadata:
           labels:
              app: mysql
         spec:
            containers:
            - name: mysql-container
              image: mysql
              ports:
              - containerPort: 8080
                protocol: TCP
              env :
                - name : MYSQL_ROOT_PASSWORD
                  valueFrom :
                    secretKeyRef:
                      name: dbconf2
                      key: passwd